-- LiftTrack Mission 6 + 7 additive migration.
-- Review and run manually in the Supabase SQL editor. This file is never executed by the app.

alter table public.nutrition_logs
  add column if not exists calories numeric check (calories is null or calories >= 0);

create table if not exists public.fitness_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  body_weight_kg numeric not null check (body_weight_kg between 20 and 400),
  goal text not null check (goal in ('build', 'maintain', 'fat_loss')),
  protein_target_override numeric check (protein_target_override is null or protein_target_override between 20 and 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.body_weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  weight_kg numeric not null check (weight_kg between 20 and 400),
  measured_on date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists body_weight_logs_user_date_idx
  on public.body_weight_logs (user_id, measured_on desc, created_at desc);

alter table public.fitness_profiles enable row level security;
alter table public.body_weight_logs enable row level security;

drop policy if exists "Users can read own fitness profile" on public.fitness_profiles;
create policy "Users can read own fitness profile" on public.fitness_profiles
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own fitness profile" on public.fitness_profiles;
create policy "Users can insert own fitness profile" on public.fitness_profiles
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own fitness profile" on public.fitness_profiles;
create policy "Users can update own fitness profile" on public.fitness_profiles
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own fitness profile" on public.fitness_profiles;
create policy "Users can delete own fitness profile" on public.fitness_profiles
  for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can read own weight logs" on public.body_weight_logs;
create policy "Users can read own weight logs" on public.body_weight_logs
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own weight logs" on public.body_weight_logs;
create policy "Users can insert own weight logs" on public.body_weight_logs
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own weight logs" on public.body_weight_logs;
create policy "Users can update own weight logs" on public.body_weight_logs
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own weight logs" on public.body_weight_logs;
create policy "Users can delete own weight logs" on public.body_weight_logs
  for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.fitness_profiles to authenticated;
grant select, insert, update, delete on public.body_weight_logs to authenticated;
grant usage, select on sequence public.body_weight_logs_id_seq to authenticated;
